source 'https://github.com/CocoaPods/Specs.git'
target 'who_mobile' do
  pod 'SQLCipher'
  pod 'Parse'
  # Add new pods below this line
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'


  # pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  # pod 'RNFS', :path => '../node_modules/react-native-fs'


end