/**
 * Created by florinpopa on 14/06/2018.
 */
// ACTION TYPES
export const ACTION_TYPE_ROOT_CHANGE = 'ROOT_CHANGE';
export const ACTION_TYPE_SAVE_SCREEN_SIZE = 'SAVE_SCREEN_SIZE';
export const ACTION_TYPE_LOGIN = 'LOGIN';
export const ACTION_TYPE_AFTER_LOGIN = 'AFTER_LOGIN';
export const ACTION_TYPE_STORE_USER = 'STORE_USER';
export const ACTION_TYPE_GET_FOLLOWUPS = 'GET_FOLLOWUPS';
export const ACTION_TYPE_STORE_FOLLOWUPS = 'STORE_FOLLOWUPS';
