/**
 * Created by florinpopa on 14/06/2018.
 */
// ACTION TYPES
export const ACTION_TYPE_ROOT_CHANGE = 'ROOT_CHANGE';
export const ACTION_TYPE_SAVE_SCREEN_SIZE = 'SAVE_SCREEN_SIZE';
export const ACTION_TYPE_SAVE_TRANSLATION = 'SAVE_TRANSLATION';
export const ACTION_TYPE_REMOVE_FILTER_FOR_SCREEN = 'REMOVE_FILTER_FOR_SCREEN';
export const ACTION_TYPE_ADD_FILTER_FOR_SCREEN = 'ADD_FILTER_FOR_SCREEN';
export const ACTION_TYPE_LOGIN = 'LOGIN';
export const ACTION_TYPE_AFTER_LOGIN = 'AFTER_LOGIN';
export const ACTION_TYPE_STORE_USER = 'STORE_USER';
export const ACTION_TYPE_GET_FOLLOWUPS = 'GET_FOLLOWUPS';
export const ACTION_TYPE_STORE_FOLLOWUPS = 'STORE_FOLLOWUPS';
export const ACTION_TYPE_UPDATE_FOLLOWUP = 'UPDATE_FOLLOWUP';
export const ACTION_TYPE_DELETE_FOLLOWUP = 'DELETE_FOLLOWUP';
export const ACTION_TYPE_GET_CASES = 'GET_CASES';
export const ACTION_TYPE_STORE_CASES = 'STORE_CASES';
export const ACTION_TYPE_STORE_CONTACTS = 'STORE_CONTACTS';
export const ACTION_TYPE_UPDATE_CONTACT = 'UPDATE_CONTACT';
export const ACTION_TYPE_STORE_EVENTS = 'STORE_EVENTS';
export const ACTION_TYPE_STORE_OUTBREAK = 'STORE_OUTBREAK';
export const ACTION_TYPE_STORE_REFERENCE_DATA = 'STORE_REFERENCE_DATA';
export const ACTION_TYPE_STORE_LOCATIONS = 'STORE_LOCATIONS';
export const ACTION_TYPE_ADD_ERROR = 'ADD_ERROR';
export const ACTION_TYPE_REMOVE_ERRORS = 'REMOVE_ERRORS';
